services:
  db:
    image: postgres:16-alpine
    container_name: titan_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: titan_fitness
    ports:
      - "5432:5432"
    volumes:
      - titan_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: titan_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - titan_redisdata:/data

volumes:
  titan_pgdata:
  titan_redisdata:
